# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/630_mass_com_calc.ipynb.

# %% auto 0
__all__ = ['get_com']

# %% ../../nbs/630_mass_com_calc.ipynb 2
import numpy as np
from .measurements_heights_module import *



# %% ../../nbs/630_mass_com_calc.ipynb 3
def get_com(Ansur):
    """
    Computes the center-of-mass (COM) coordinates for the various segments.
    Returns a dictionary of COM points.
    """
    m = get_measurements(Ansur)
    heights = get_heights(Ansur)
    m=m.iloc[0]
    heights = heights.iloc[0]

    # Extract variables needed for COM calculations
    a1 = m["a1"]
    h1 = m["h1"]
    h2 = m["h2"]
    h3 = m["h3"]
    h4 = m["h4"]
    h6 = m["h6"]
    a5 = m["a5"]
    r1thigh = m["r1thigh"]
    r2thigh = m["r2thigh"]
    # For upper arm, lower arm, etc.
    h8 = m["h8"]
    r1 = m["r1"]
    r2 = m["r2"]
    h10 = m["h10"]
    r3 = m["r3"]
    r4 = m["r4"]

    a2 = m["a2"]
    b2 = m["b2"]
    a3 = m["a3"]
    b3 = m["b3"]
    a4 = m["a4"]

    a7 = m["a7"]

    # Upper trunk COM
    UTMCL = [0, h1 / 2]
    UTMC = [0, (h1 / 2 + h2 + h3 + h4 + h6 + a5 * 2)]

    # Head COM
    HeMCL = [0, a7]
    height_total = m["h1"] + m["h2"] + m["h3"] + m["h4"] + h6 + a5 * 2 + a7 * 2
    HeMC = [0, (height_total - a7)]

    # Middle trunk COM
    R_top = np.sqrt((a2**2 + b2**2) / 2)
    R_bot = np.sqrt((a3**2 + b3**2) / 2)
    MTMCLz = h2 - (h2 / 4 * ((R_top**2 + 2 * R_top * R_bot + 3 * R_bot**2) /
                              (R_top**2 + R_top * R_bot + R_bot**2)))
    MTMCL = [0, MTMCLz]
    MTMC = [0, (MTMCLz + h3 + h4 + h6 + a5 * 2)]

    # Lower trunk COM
    LTMCL = [0, h3 / 2]
    LTMC = [0, (h3 / 2 + h4 + h6 + a5 * 2)]

    # Left Thigh COM
    LTHMCz = h4 - (h4 * (3 * r2thigh**2 + 2 * r2thigh * r1thigh + r1thigh**2)) / (4 * (r2thigh**2 + r2thigh * r1thigh + r1thigh**2))
    LTHMCL = [-r1thigh, LTHMCz]
    LTHMC = [-r1thigh, LTHMCz + h6 + 2 * a5]

    # Right Thigh COM
    RTHMCz = h4 - (h4 * (3 * r2thigh**2 + 2 * r2thigh * r1thigh + r1thigh**2)) / (4 * (r2thigh**2 + r2thigh * r1thigh + r1thigh**2))
    RTHMCL = [r1thigh, RTHMCz]
    RTHMC = [r1thigh, RTHMCz + h6 + 2 * a5]

    thighdelta = r1thigh - r2thigh

    # Left Shank COM
    LSHMCz = h6 - (h6 * (3 * m["r2shank"]**2 + 2 * m["r2shank"] * m["r1shank"] + m["r1shank"]**2)) / (4 * (m["r2shank"]**2 + m["r2shank"] * m["r1shank"] + m["r1shank"]**2))
    LSHMCL = [0, LSHMCz]
    LSHMC = [-(thighdelta + m["r1shank"]), 2 * a5 + LSHMCz]

    # Right Shank COM
    RSHMCz = h6 - (h6 * (3 * m["r2shank"]**2 + 2 * m["r2shank"] * m["r1shank"] + m["r1shank"]**2)) / (4 * (m["r2shank"]**2 + m["r2shank"] * m["r1shank"] + m["r1shank"]**2))
    RSHMCL = [0, RSHMCz]
    RSHMC = [(thighdelta + m["r1shank"]), 2 * a5 + RSHMCz]

    # Left Upper Arm COM
    LUAMCz = h8 - (h8 * (3 * r2**2 + 2 * r2 * r1 + r1**2)) / (4 * (r2**2 + r2 * r1 + r1**2))
    LUAMCL = [0, LUAMCz]
    LUAMC = [-(a1 + r1), heights["UpperArmH"] + LUAMCz]

    # Right Upper Arm COM
    RUAMCz = h8 - (h8 * (3 * r2**2 + 2 * r2 * r1 + r1**2)) / (4 * (r2**2 + r2 * r1 + r1**2))
    RUAMCL = [0, RUAMCz]
    RUAMC = [a1 + r1, heights["UpperArmH"] + RUAMCz]

    # Left Lower Arm COM
    LLAMCz = h10 - (h10 * (3 * r4**2 + 2 * r4 * r3 + r3**2)) / (4 * (r4**2 + r4 * r3 + r3**2))
    LLAMCL = [0, LLAMCz]
    LLAMC = [-(a1 + r1), heights["LowerArmH"] + LLAMCz]

    # Right Lower Arm COM
    RLAMCz = h10 - (h10 * (3 * r4**2 + 2 * r4 * r3 + r3**2)) / (4 * (r4**2 + r4 * r3 + r3**2))
    RLAMCL = [0, RLAMCz]
    RLAMC = [a1 + r1, heights["LowerArmH"] + RLAMCz]

    # Left Foot COM
    LFMCx = m["h7"] - (m["h7"] * (3 * m["a6"]**2 + 2 * m["a6"] * a5 + a5**2)) / (4 * (m["a6"]**2 + m["a6"] * a5 + a5**2))
    LFMCL = [LFMCx, a5]
    LFMC = [-(thighdelta + m["r1shank"]), a5]

    # Right Foot COM
    RFMCx = m["h7"] - (m["h7"] * (3 * m["a6"]**2 + 2 * m["a6"] * a5 + a5**2)) / (4 * (m["a6"]**2 + m["a6"] * a5 + a5**2))
    RFMCL = [RFMCx, a5]
    RFMC = [(thighdelta + m["r1shank"]), a5]

    com = {
        "UTMCL": UTMCL, "UTMC": UTMC,
        "HeMCL": HeMCL, "HeMC": HeMC,
        "MTMCL": MTMCL, "MTMC": MTMC,
        "LTMCL": LTMCL, "LTMC": LTMC,
        "LTHMCL": LTHMCL, "LTHMC": LTHMC,
        "RTHMCL": RTHMCL, "RTHMC": RTHMC,
        "LSHMCL": LSHMCL, "LSHMC": LSHMC,
        "RSHMCL": RSHMCL, "RSHMC": RSHMC,
        "LUAMCL": LUAMCL, "LUAMC": LUAMC,
        "RUAMCL": RUAMCL, "RUAMC": RUAMC,
        "LLAMCL": LLAMCL, "LLAMC": LLAMC,
        "RLAMCL": RLAMCL, "RLAMC": RLAMC,
        "LFMCL": LFMCL, "LFMC": LFMC,
        "RFMCL": RFMCL, "RFMC": RFMC
    }
    return com

