# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/670_mass_clauser.ipynb.

# %% auto 0
__all__ = ['clauser']

# %% ../../nbs/670_mass_clauser.ipynb 1
import numpy as np

# %% ../../nbs/670_mass_clauser.ipynb 2
def clauser(ansur,inputweight, inputheight):

    # Actual mass from input
    M = inputweight

    # Parameters used in the modified Hanavan model (converted to cm)
    # Hand
    P15 = ansur['wristcircumference'] / 10         # value in cm
    P32 = ansur['wristcircumference'] / (np.pi * 10) # circumference in cm

    # Forearm
    # Note: Original code reused P15; we do the same here.
    P15 = ansur['wristcircumference'] / 10         # cm
    P16 = ansur['forearmcircumferenceflexed']*0.97 / 10

    # Upperarm
    P18 = ansur['bicepscircumferenceflexed']*0.91 / 10
    P5  = ansur['acromionradialelength'] / 10

    # Foot
    P22 = ansur['anklecircumference'] / 10
    P6  = ansur['footlength'] / 10

    # Shank
    P23 = ansur['calfcircumference'] / 10

    # Thigh
    P25 = ansur['thighcircumference'] / 10

    # Head
    P26 = ansur['headcircumference'] / 10

    # Trunk
    P41 = (((ansur['eyeheightsitting']+inputheight-ansur['sittingheight'])-ansur['mentonsellionlength'])-ansur['trochanterionheight'])/10

    P27 = ansur['chestcircumference'] / 10

    # Compute segment masses using the provided formulas:

    # Hand
    mH = 0.038 * P15 + 0.080 * P32 - 0.660

    # Forearm
    mLA = 0.081 * P15 + 0.052 * P16 - 1.650

    # Upperarm
    mUA = 0.007 * M + 0.092 * P18 + 0.050 * P5 - 3.101

    # Foot
    mF = 0.003 * M + 0.048 * P22 + 0.027 * P6 - 0.869

    # Shank
    mS = 0.135 * P23 - 1.318

    # Thigh
    mTh = 0.074 * M + 0.138 * P25 - 4.641

    # Head
    mHe = 0.104 * P26 + 0.015 * M - 2.189

    # Trunk
    mTr = 0.349 * M + 0.423 * P41 + 0.229 * P27 - 35.460

    # Total estimated mass:
    mTOT = 2 * (mH + mLA + mUA + mF + mS + mTh) + mHe + mTr

    diff = ((mTOT - M) / M) * 100

    # Build and return a dictionary with results
    weights = {
        "diff": diff,
        "diff_kg": mTOT - M,
        "Weight_actual": M,
        "mTOT": mTOT,
        "mH": mH,
        "mLA": mLA,
        "mUA": mUA,
        "mF": mF,
        "mS": mS,
        "mTh": mTh,
        "mHe": mHe,
        "mTr": mTr,
        "mTOT": mTOT
    }
    return weights



