# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/600_mass.ipynb.

# %% auto 0
__all__ = ['main']

# %% ../../nbs/600_mass.ipynb 3
from .com_calculation_module import *
from .com_calculation_module import *
from .volume_calculation_module import *
from .plot_body_module import *
from .inertial_calc_module import *
from .massclauser_module import *
from .measurements_heights_module import get_measurements, get_heights
import pandas as pd



# %% ../../nbs/600_mass.ipynb 5
def main(Ansur, inputweight, inputheight, gender):
    

    #Gathers librarys from other function
    heights = get_heights(Ansur, inputheight).iloc[0]
    pointsJC, com = get_joint_and_com_points(Ansur, inputheight, gender)
    weights = clauser(Ansur.iloc[0], inputweight, inputheight)
    weightsZat = zatsiorsky(inputweight, inputheight)
    inertia = calculate_inertia(Ansur, inputweight, inputheight)

    






    print(".......................................................")

    #Prints information about height and total estimated weight
    print("RESULTS:")
    print("Estimated Height (m):", heights["TotalH"])
    print("Actual Height (m):", inputheight/1000)
    print("Total Estimated Weight (kg) using Clauser regression model",weights['mTOT'] )
    print("Total Estimated Weight (kg) using Zatriosky regression model",weightsZat['mTOTzat'] )




    print(".......................................................")




    #Prints the COM positions and aranges in dataframe
    segments = [
        'Head', 'Upper Trunk', 'Middle Trunk', 'Lower Trunk', 'Upper Arm',
        'Lower Arm', 'Hand', 'Thigh', 'Shank', 'Foot'
    ]

    #Please note: COM positions are stored like 2D coordinates (y, z). Since all of them (exept foot) are placed on (x = 0) 
    #Ex: com("U(Upper)T(Trunk)M(Mass)C(Center)")[0] gives y coordinate for upper trunk
    positions_df = pd.DataFrame(index=['X', 'Y', 'Z'], columns=segments)

    positions_df.loc[:, 'Head'] = [0, round(com['HeMC'][0], 3), round(com['HeMC'][1], 3)]
    positions_df.loc[:, 'Upper Trunk'] = [0, round(com['UTMC'][0], 3), round(com['UTMC'][1], 3)]
    positions_df.loc[:, 'Middle Trunk'] = [0, round(com['MTMC'][0], 3), round(com['MTMC'][1], 3)]
    positions_df.loc[:, 'Lower Trunk'] = [0, round(com['LTMC'][0], 3), round(com['LTMC'][1], 3)]
    positions_df.loc[:, 'Upper Arm'] = [0, round(com['RUAMC'][0], 3), round(com['RUAMC'][1], 3)]
    positions_df.loc[:, 'Lower Arm'] = [0, round(com['RLAMC'][0], 3), round(com['RLAMC'][1], 3)]
    positions_df.loc[:, 'Hand'] = [0, round(com['RHMC'][0], 3), round(com['RHMC'][1], 3)]
    positions_df.loc[:, 'Thigh'] = [0, round(com['RTHMC'][0], 3), round(com['RTHMC'][1], 3)]
    positions_df.loc[:, 'Shank'] = [0, round(com['RSHMC'][0], 3), round(com['RSHMC'][1], 3)]
    positions_df.loc[:, 'Foot'] = [0, round(com['RFMC'][0], 3), round(com['RFMC'][1], 3)]

    print("\nPositions of Body Segments (Custom Cartesian Mapping)\n")
    print(positions_df.to_string())


    print(".......................................................")


    #Prints the joint center positions and aranges in dataframe
    #Please note: joint positions are stored like 2D coordinates (y, z). Since all of them are placed on (x = 0) 

    joints = ["Shoulder", "Elbow", "Wrist", "Hip", "Knee", "Ankle"]

    #Create the DataFrame
    jc_positions_df = pd.DataFrame(index=['X', 'Y', 'Z'], columns=joints)

    #Fill the table with absolute Y values 
    for joint in joints:
        coords = pointsJC[joint]
        y_depth = round(abs(coords[0]), 3)   # take absolute value of Y (distance from centerline)
        z_height = round(coords[1], 3)
        jc_positions_df.loc[:, joint] = [0, y_depth, z_height]

    # Display the table
    print("\nJoint Center Positions\n")
    print(jc_positions_df.to_string())


    print(".......................................................")







    #Print masses from clausers estimation of mass
    #This only useses one segment for trunk
    #Segment masses correspond to 2D and 3D visualisation
    mass_segments = [
        "Head", "Trunk Total", "Upper Trunk", "Middle Trunk", "Lower Trunk",
        "Upper Arm", "Forearm", "Hand", "Thigh", "Shank", "Foot"
    ]

    # Create mass comparison table
    mass_df = pd.DataFrame(index=["Clauser", "Zatsiorsky"], columns=mass_segments)

    # --- Clauser Values ---
    mass_df.loc["Clauser", "Head"] = round(weights["mHe"], 3)
    mass_df.loc["Clauser", "Trunk Total"] = round(weights["mTr"], 3)
    mass_df.loc["Clauser", "Upper Trunk"] = "---"
    mass_df.loc["Clauser", "Middle Trunk"] = "---"
    mass_df.loc["Clauser", "Lower Trunk"] = "---"
    mass_df.loc["Clauser", "Upper Arm"] = round(weights["mUA"], 3)
    mass_df.loc["Clauser", "Forearm"] = round(weights["mLA"], 3)
    mass_df.loc["Clauser", "Hand"] = round(weights["mH"], 3)
    mass_df.loc["Clauser", "Thigh"] = round(weights["mTh"], 3)
    mass_df.loc["Clauser", "Shank"] = round(weights["mS"], 3)
    mass_df.loc["Clauser", "Foot"] = round(weights["mF"], 3)








    #Print masses from zatsiorsky estimation of mass
    #This useses 3 segments for trunk
    #Segment masses DOES NOT correspond to 2D and 3D visualisation
    # --- Zatsiorsky Values ---
    trunk_total_zat = (
        weightsZat["mUppTrzat"] +
        weightsZat["mMidTrzat"] +
        weightsZat["mLowTrzat"]
    )

    mass_df.loc["Zatsiorsky", "Head"] = round(weightsZat["mHezat"], 3)
    mass_df.loc["Zatsiorsky", "Trunk Total"] = round(trunk_total_zat, 3)
    mass_df.loc["Zatsiorsky", "Upper Trunk"] = round(weightsZat["mUppTrzat"], 3)
    mass_df.loc["Zatsiorsky", "Middle Trunk"] = round(weightsZat["mMidTrzat"], 3)
    mass_df.loc["Zatsiorsky", "Lower Trunk"] = round(weightsZat["mLowTrzat"], 3)
    mass_df.loc["Zatsiorsky", "Upper Arm"] = round(weightsZat["mUAzat"], 3)
    mass_df.loc["Zatsiorsky", "Forearm"] = round(weightsZat["mLAzat"], 3)
    mass_df.loc["Zatsiorsky", "Hand"] = round(weightsZat["mHzat"], 3)
    mass_df.loc["Zatsiorsky", "Thigh"] = round(weightsZat["mThzat"], 3)
    mass_df.loc["Zatsiorsky", "Shank"] = round(weightsZat["mSzat"], 3)
    mass_df.loc["Zatsiorsky", "Foot"] = round(weightsZat["mFzat"], 3)

    # --- Display the table ---
    print("\nSegment Mass Comparison (kg) — Detailed Trunk View\n")
    print(mass_df.to_string())




#Prints moments of inertia:
    print(f"{'Upper Trunk':<12} {inertia['Ixx_UT']:>12.4f} {inertia['Iyy_UT']:>12.4f} {inertia['Izz_UT']:>12.4f}")
    print(f"{'Middle Trunk':<12} {inertia['Ixx_MT']:>12.4f} {inertia['Iyy_MT']:>12.4f} {inertia['Izz_MT']:>12.4f}")
    print(f"{'Lower Trunk':<12} {inertia['Ixx_LT']:>12.4f} {inertia['Iyy_LT']:>12.4f} {inertia['Izz_LT']:>12.4f}")

    print(f"{'Thigh':<12} {inertia['Ixx_T']:>12.4f} {inertia['Iyy_T']:>12.4f} {inertia['Izz_T']:>12.4f}")
    print(f"{'Shank':<12} {inertia['Ixx_S']:>12.4f} {inertia['Iyy_S']:>12.4f} {inertia['Izz_S']:>12.4f}")
    print(f"{'Foot':<12} {inertia['Ixx_F']:>12.4f} {inertia['Iyy_F']:>12.4f} {inertia['Izz_F']:>12.4f}")

    print(f"{'Upper Arm':<12} {inertia['Ixx_UA']:>12.4f} {inertia['Iyy_UA']:>12.4f} {inertia['Izz_UA']:>12.4f}")
    print(f"{'Lower Arm':<12} {inertia['Ixx_LA']:>12.4f} {inertia['Iyy_LA']:>12.4f} {inertia['Izz_LA']:>12.4f}")
    print(f"{'Hand':<12} {inertia['Ixx_Ha']:>12.4f} {inertia['Iyy_Ha']:>12.4f} {inertia['Izz_Ha']:>12.4f}")
    print(f"{'Head':<12} {inertia['Ixx_H']:>12.4f} {inertia['Iyy_H']:>12.4f} {inertia['Izz_H']:>12.4f}")



    # Draw the plot
    plot_body(Ansur, inputheight, gender)

    

    
    

