# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/610_mass.ipynb.

# %% auto 0
__all__ = ['get_measurements', 'get_heights']

# %% ../../nbs/610_mass.ipynb 2
import numpy as np
import pandas as pd
# This file computes the intermediate measurements and heights.
# Note: The Ansur list is not defined here; you will pass it as a parameter.

# %% ../../nbs/610_mass.ipynb 3
def get_measurements(Ansur):
    measurements = pd.DataFrame()
    # Upper trunk
    measurements["a1"] = Ansur['biacromialbreadth'] / 2000
    measurements["b1"] = Ansur['chestdepth'] / 2000
    measurements["h1"] = (Ansur['cervicaleheight'] - Ansur['axillaheight']) / 1000  # D21

    # Middle trunk
    measurements["h2"] = (Ansur['axillaheight'] - Ansur['waistheightomphalion']) / 1000  # D5
    measurements["a2"] = Ansur['biacromialbreadth'] / 2000
    measurements["b2"] = Ansur['chestdepth'] / 2000
    measurements["a3"] = Ansur['waistbreadth'] / 2000
    measurements["b3"] = Ansur['waistdepth'] / 2000

    # Lower trunk
    measurements["a4"] = Ansur['waistbreadth'] / 2000
    measurements["b4"] = Ansur['waistdepth'] / 2000
    measurements["h3"] = (Ansur['iliocristaleheight'] - Ansur['trochanterionheight']) / 1000  # D22

    # Thigh
    measurements["h4"] = (Ansur['trochanterionheight'] - Ansur['lateralfemoralepicondyleheight']) / 1000  # D29
    measurements["c1"] = Ansur['thighcircumference'] / 1000  # circumference
    measurements["c2"] = Ansur['lowerthighcircumference'] / 1000
    measurements["r1thigh"] = measurements["c1"] / (2 * np.pi)
    measurements["r2thigh"] = measurements["c2"] / (2 * np.pi)

    # Shank
    measurements["h6"] = (Ansur['lateralfemoralepicondyleheight'] - Ansur['lateralmalleolusheight']) / 1000  # D6
    measurements["c3"] = Ansur['lowerthighcircumference'] / 1000
    measurements["c4"] = Ansur['anklecircumference'] / 1000
    measurements["r1shank"] = measurements["c3"] / (2 * np.pi)
    measurements["r2shank"] = measurements["c4"] / (2 * np.pi)

    # Foot
    measurements["a5"] = (Ansur['heelanklecircumference'] / 1000) / (2 * np.pi)
    measurements["b5"] = (Ansur['heelanklecircumference'] / 1000) / (2 * np.pi)
    measurements["a6"] = (((Ansur['footbreadthhorizontal'] / 1000) + ((Ansur['footbreadthhorizontal'] / 1000) / 4)) / 4)
    measurements["b6"] = (((Ansur['balloffootcircumference'] / 1000) + ((Ansur['footbreadthhorizontal'] / 1000) / 2)) / (2 * np.pi)) - measurements["a6"]
    measurements["h7"] = Ansur['footlength'] / 1000

    # Upper arm
    measurements["r1"] = (Ansur['bicepscircumferenceflexed'] / 1000) / (2 * np.pi)
    measurements["r2"] = (Ansur['forearmcircumferenceflexed'] / 1000) / (2 * np.pi)
    measurements["h8"] = Ansur['shoulderelbowlength'] / 1000

    # Hand
    measurements["c7"] = Ansur['handcircumference'] / 2000
    measurements["h9"] = Ansur['handlength'] / 2000
    measurements["b7"] = Ansur['handbreadth'] / 2000

    # Head
    measurements["b8"] = Ansur['headbreadth'] / 2000
    measurements["a7"] = Ansur['tragiontopofhead'] / 1000

    # Lower arm
    measurements["h10"] = (Ansur['forearmhandlength'] - Ansur['handlength']) / 1000  # D15
    measurements["r3"] = (Ansur['forearmcircumferenceflexed'] / 1000) / (2 * np.pi)
    measurements["r4"] = (Ansur['wristcircumference'] / 1000) / (2 * np.pi)

    return measurements


# %% ../../nbs/610_mass.ipynb 4
def get_heights(Ansur):
    m = get_measurements(Ansur)
    #heights = {}
    heights = pd.DataFrame()
    # Compute trunk height as in your original code:
    # (h1+h2+h3+h4+h6 + 2*a5) which is used for head and arms
    trunk_height = m["h1"] + m["h2"] + m["h3"] + m["h4"] + m["h6"] + m["a5"] * 2
    # Total estimated height (includes head length, 2*a7)
    total_height = trunk_height + m["a7"] * 2
    
    # For plotting body segments (trunk, arms, etc.), use trunk_height
    heights["TrunkH"] = trunk_height  
    heights["TotalH"] = total_height   # overall estimated height
    
    heights["UpperTrunkH"] = m["a5"] * 2 + m["h6"] + m["h4"] + m["h3"] + m["h2"]
    heights["MiddleTrunkH"] = m["a5"] * 2 + m["h6"] + m["h4"] + m["h3"]
    heights["LowerTrunkH"] = m["a5"] * 2 + m["h6"] + m["h4"]
    heights["ThighH"] = m["a5"] * 2 + m["h6"]
    heights["ShankH"] = 2 * m["a5"]
    # Arms are positioned relative to the trunk height:
    heights["UpperArmH"] = trunk_height - m["h8"]
    heights["LowerArmH"] = heights["UpperArmH"] - m["h10"]
    heights["FootH"] = 0  # as specified
    return heights

