# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/640_mass_plot_body.ipynb.

# %% auto 0
__all__ = ['plot_body']

# %% ../../nbs/640_mass_plot_body.ipynb 2
import matplotlib.pyplot as plt
from matplotlib.patches import Ellipse, Polygon
from .measurements_heights_module import *
from .com_calculation_module import *

# %% ../../nbs/640_mass_plot_body.ipynb 3
def plot_body(Ansur):
    """
    Draws a front-view plot of the body segments with COM points.
    """
    m = get_measurements(Ansur)
    heights = get_heights(Ansur)
    com = get_com(Ansur)

    m = m.iloc[0]
    heights = heights.iloc[0]
    #com = com.iloc[0]
    # Extract variables for drawing
    r1 = m["r1"]
    r2 = m["r2"]
    h8 = m["h8"]
    a1 = m["a1"]
    h1 = m["h1"]
    a2 = m["a2"]
    b2 = m["b2"]
    a3 = m["a3"]
    b3 = m["b3"]
    a4 = m["a4"]
    h3 = m["h3"]
    h4 = m["h4"]
    h6 = m["h6"]
    a5 = m["a5"]
    r1thigh = m["r1thigh"]
    r2thigh = m["r2thigh"]
    thighdelta = r1thigh - r2thigh

    # Use trunk height (base for head and arms) from get_heights
    TrunkH = heights["TrunkH"]
    UpperTrunkH = heights["UpperTrunkH"]
    MiddleTrunkH = heights["MiddleTrunkH"]
    LowerTrunkH = heights["LowerTrunkH"]
    ThighH = heights["ThighH"]
    ShankH = heights["ShankH"]
    UpperArmH = heights["UpperArmH"]
    LowerArmH = heights["LowerArmH"]
    TotalH = heights["TotalH"]

    # COM points (2D projection)
    points = {
        "Upper Trunk": com["UTMC"],
        "Middle Trunk": com["MTMC"],
        "Lower Trunk": com["LTMC"],
        "Head": com["HeMC"],
        "Left Thigh": com["LTHMC"],
        "Right Thigh": com["RTHMC"],
        "Left Shank": com["LSHMC"],
        "Right Shank": com["RSHMC"],
        "Left Upper Arm": com["LUAMC"],
        "Right Upper Arm": com["RUAMC"],
        "Left Lower Arm": com["LLAMC"],
        "Right Lower Arm": com["RLAMC"],
        "Left Foot": com["LFMC"],
        "Right Foot": com["RFMC"],
    }

    # Create figure
    fig, ax = plt.subplots(figsize=(8, 8))

    # Plot COM points
    for label, (x, y) in points.items():
        ax.scatter(x, y, color='red')
        ax.text(x + 0.05, y, label, fontsize=8)

    # Draw body segment shapes

    # Upper Trunk (Rectangle)
    upper_trunk_coords = [
        (-a1, UpperTrunkH),
        (a1, UpperTrunkH),
        (a1, UpperTrunkH + h1),
        (-a1, UpperTrunkH + h1)
    ]
    ax.add_patch(Polygon(upper_trunk_coords, closed=True, fill=False, edgecolor='blue'))

    # Middle Trunk (Trapezoid)
    middle_trunk_coords = [
        (-a2, MiddleTrunkH + m["h2"]),
        (a2, MiddleTrunkH + m["h2"]),
        (a3, MiddleTrunkH),
        (-a3, MiddleTrunkH)
    ]
    ax.add_patch(Polygon(middle_trunk_coords, closed=True, fill=False, edgecolor='green'))

    # Lower Trunk (Rectangle)
    lower_trunk_coords = [
        (-a4, LowerTrunkH),
        (a4, LowerTrunkH),
        (a4, LowerTrunkH + h3),
        (-a4, LowerTrunkH + h3)
    ]
    ax.add_patch(Polygon(lower_trunk_coords, closed=True, fill=False, edgecolor='blue'))

    # Left Thigh (Rectangle)
    left_thigh_coords = [
        (-((r1thigh - r2thigh) + 2 * r2thigh), ThighH),
        (-(r1thigh - r2thigh), ThighH),
        (0, ThighH + h4),
        (-2 * r1thigh, ThighH + h4)
    ]
    ax.add_patch(Polygon(left_thigh_coords, closed=True, fill=False, edgecolor='red'))

    # Right Thigh (Rectangle)
    right_thigh_coords = [
        (((r1thigh - r2thigh) + 2 * r2thigh), ThighH),
        ((r1thigh - r2thigh), ThighH),
        (0, ThighH + h4),
        (2 * r1thigh, ThighH + h4)
    ]
    ax.add_patch(Polygon(right_thigh_coords, closed=True, fill=False, edgecolor='red'))

    # Left Shank (Rectangle)
    left_shank_coords = [
        (-((m["r1shank"] - m["r2shank"]) + 2 * m["r2shank"] + thighdelta), ShankH),
        (-(m["r1shank"] - m["r2shank"]) - thighdelta, ShankH),
        (-(thighdelta), ShankH + h6),
        (-(2 * m["r1shank"] + thighdelta), ShankH + h6)
    ]
    ax.add_patch(Polygon(left_shank_coords, closed=True, fill=False, edgecolor='red'))

    # Right Shank (Rectangle)
    right_shank_coords = [
        (((m["r1shank"] - m["r2shank"]) + 2 * m["r2shank"] + thighdelta), ShankH),
        (((m["r1shank"] - m["r2shank"]) + thighdelta), ShankH),
        ((thighdelta), ShankH + h6),
        ((2 * m["r1shank"] + thighdelta), ShankH + h6)
    ]
    ax.add_patch(Polygon(right_shank_coords, closed=True, fill=False, edgecolor='red'))

    # Left Upper Arm (Rectangle)
    left_upperarm_coords = [
        (-(-(r1 - m["r2"]) + r1 * 2 + a1), UpperArmH),
        (-((r1 - m["r2"]) + a1), UpperArmH),
        (-a1, UpperArmH + h8),
        (-(a1 + (r1 * 2)), UpperArmH + h8)
    ]
    ax.add_patch(Polygon(left_upperarm_coords, closed=True, fill=False, edgecolor='red'))

    # Right Upper Arm (Rectangle)
    right_upperarm_coords = [
        (((-(r1 - m["r2"]) + r1 * 2 + a1)), UpperArmH),
        (((r1 - m["r2"]) + a1), UpperArmH),
        (a1, UpperArmH + h8),
        ((a1 + (r1 * 2)), UpperArmH + h8)
    ]
    ax.add_patch(Polygon(right_upperarm_coords, closed=True, fill=False, edgecolor='red'))

    ULdelta = (r1 - m["r3"])  # Distance between upper and lower arm centers

    # Left Lower Arm (Rectangle)
    left_lowerarm_coords = [
        (-(-(m["r3"] - m["r4"]) + m["r3"] * 2 + a1 + ULdelta), LowerArmH),
        (-((m["r3"] - m["r4"]) + a1 + ULdelta), LowerArmH),
        (-(a1 + ULdelta), LowerArmH + m["h10"]),
        (-(a1 + (m["r3"] * 2) + ULdelta), LowerArmH + m["h10"])
    ]
    ax.add_patch(Polygon(left_lowerarm_coords, closed=True, fill=False, edgecolor='red'))

    # Right Lower Arm (Rectangle)
    right_lowerarm_coords = [
        (((-(m["r3"] - m["r4"]) + m["r3"] * 2 + a1 + ULdelta), LowerArmH)),
        (((m["r3"] - m["r4"]) + a1 + ULdelta), LowerArmH),
        ((a1 + ULdelta), LowerArmH + m["h10"]),
        ((a1 + (m["r3"] * 2) + ULdelta), LowerArmH + m["h10"])
    ]
    ax.add_patch(Polygon(right_lowerarm_coords, closed=True, fill=False, edgecolor='red'))

    # Left Foot (Ellipse)
    ax.add_patch(Ellipse((-(thighdelta + m["r1shank"]), a5), a5 * 2, a5 * 2,
                         fill=False, edgecolor='purple', linewidth=1.5))
    # Right Foot (Ellipse)
    ax.add_patch(Ellipse(((thighdelta + m["r1shank"]), a5), a5 * 2, a5 * 2,
                         fill=False, edgecolor='purple', linewidth=1.5))
    # Head (Ellipse) - position the head on top of the trunk height
    ax.add_patch(Ellipse((0, TrunkH + m["a7"]), m["b8"] * 2, m["a7"] * 2,
                         fill=False, edgecolor='purple', linewidth=1.5))

    # Axes styling
    ax.axhline(0, color='black')
    ax.axvline(0, color='black')
    ax.set_title("Body Segments with Center of Mass (Front view)")
    ax.set_xlabel("x")
    ax.set_ylabel("y")
    ax.set_xlim(-1.25, 1.25)
    ax.set_ylim(0, 2.5)
    ax.set_aspect('equal')
    ax.grid(True)
    plt.show()

