# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/201_anthropometry.ipynb.

# %% auto 0
__all__ = ['make_pickle', 'model_bmb', 'predict_mean_bmb']

# %% ../nbs/201_anthropometry.ipynb 2
import pickle
import pandas as pd
import arviz as az
import bambi as bmb

# %% ../nbs/201_anthropometry.ipynb 3
def make_pickle(model, kindofmodel, measurement):
    with open(f'../output/anthro_models/{kindofmodel}/pickle_{measurement}_{kindofmodel}','wb') as file:
        pickle.dump(model,file)

# %% ../nbs/201_anthropometry.ipynb 5
def model_bmb(measurement):
    train=pd.read_csv('../data/processed/ANSURIInormalizedtrain.csv')
    variables = f"{measurement} ~ weightkg + stature + Gender"
    made_model = bmb.Model(variables, data=train)
    return made_model

# %% ../nbs/201_anthropometry.ipynb 6
def predict_mean_bmb(fitted, model, data, measurement):
    pred_df=pd.DataFrame()
    model.predict(fitted, data = data, kind='response')
    posterior_predictive = az.extract(fitted, group="posterior_predictive")
    predictions = posterior_predictive[measurement]
    mean_pred=[]
    for row in predictions:
        mean_pred.append(row.values.mean())    
    pred_df['neckcircumference']=mean_pred
    return pred_df
