# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/230_anthro_bambi.ipynb.

# %% auto 0
__all__ = ['setpriors_com', 'component_model']

# %% ../nbs/230_anthro_bambi.ipynb 4
import pandas as pd
import bambi as bmb
from .anthro_module import *

# %% ../nbs/230_anthro_bambi.ipynb 7
def setpriors_com(measurement, data):

    mean = data[measurement].mean()
    sd = data[measurement].std()

    mean_weight = data['weightkg'].mean()   
    mean_stature = data['stature'].mean()   

    priors = {
        "Intercept": bmb.Prior("Normal", mu=mean, sigma=sd*3),
        "Gender": bmb.Prior("Normal", mu=0, sigma=1),
        "weightkg": bmb.Prior("Normal", mu=mean/mean_weight, sigma=1),
        "stature": bmb.Prior("Normal", mu=mean/mean_stature, sigma=1),
        "Gender|Component": bmb.Prior("Normal", mu=0, sigma=bmb.Prior("Exponential", lam=1)),
        "sigma": bmb.Prior("Exponential", lam=1),
    }
    return priors
    

# %% ../nbs/230_anthro_bambi.ipynb 9
def component_model(measurement, data):
    model = bmb.Model(
    formula=f"{measurement} ~ 1 + Gender + weightkg + stature + (0 + Gender|Component)",
    data=data,
    priors=setpriors_com(measurement, data),
    noncentered=True
    )
    return model

