# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/221_anthro_bambi.ipynb.

# %% auto 0
__all__ = ['make_model']

# %% ../nbs/221_anthro_bambi.ipynb 1
import pandas as pd
import bambi as bmb
from .anthro_module import *

# %% ../nbs/221_anthro_bambi.ipynb 3
def make_model(measurement, data, formula:str):
    variables = f"{measurement} ~ " + formula
    made_model = bmb.Model(variables,data=data)
    made_fitted = made_model.fit(tune=2000, draws=2000, chains = 4, cores= 1, init="adapt_diag", progressbar=True)
    return made_model, made_fitted
