# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/670_mass_clauser.ipynb.

# %% auto #0
__all__ = ['clauser', 'zatsiorsky']

# %% ../../nbs/670_mass_clauser.ipynb #43db43c4
import numpy as np

# %% ../../nbs/670_mass_clauser.ipynb #483e9f0c
def clauser(ansur,inputweight, inputheight):

    # Actual mass from input
    M = inputweight

    # Parameters used in the modified Hanavan model (converted to cm)
    # Hand
    P15 = ansur['wristcircumference'] / 10         # value in cm
    P32 = ansur['wristcircumference'] / (np.pi * 10) # circumference in cm

    # Forearm
    # Note: Original code reused P15; we do the same here.
    P15 = ansur['wristcircumference'] / 10         # cm
    P16 = ansur['forearmcircumferenceflexed']*0.97 / 10

    # Upperarm
    P18 = ansur['bicepscircumferenceflexed']*0.91 / 10
    P5  = ansur['acromionradialelength'] / 10

    # Foot
    P22 = ansur['anklecircumference'] / 10
    P6  = ansur['footbreadthhorizontal']/10*2*np.pi / 10

    # Shank
    P23 = ansur['calfcircumference'] / 10

    # Thigh
    P25 = ansur['thighcircumference'] / 10

    # Head
    P26 = ansur['headcircumference'] / 10

    # Trunk
    P41 = (((ansur['eyeheightsitting']+inputheight-ansur['sittingheight'])-ansur['mentonsellionlength'])-ansur['trochanterionheight'])/10

    P27 = ansur['chestcircumference'] / 10

    # Compute segment masses using the provided formulas:

    # Hand
    mH = 0.038 * P15 + 0.080 * P32 - 0.660

    # Forearm
    mLA = 0.081 * P15 + 0.052 * P16 - 1.650

    # Upperarm
    mUA = 0.007 * M + 0.092 * P18 + 0.050 * P5 - 3.101

    # Foot
    mF = 0.003 * M + 0.048 * P22 + 0.027 * P6 - 0.869

    # Shank
    mS = 0.135 * P23 - 1.318

    # Thigh
    mTh = 0.074 * M + 0.138 * P25 - 4.641

    # Head
    mHe = 0.104 * P26 + 0.015 * M - 2.189

    # Trunk
    mTr = 0.349 * M + 0.423 * P41 + 0.229 * P27 - 35.460 

    # Total estimated mass:
    mTOT = 2 * (mH + mLA + mUA + mF + mS + mTh) + mHe + mTr

    diff = ((mTOT - M) / M) * 100

    # Build and return a dictionary with results
    weights = {
        "diff": diff,
        "diff_kg": mTOT - M,
        "Weight_actual": M,
        "mTOT": mTOT,
        "mH": mH,
        "mLA": mLA,
        "mUA": mUA,
        "mF": mF,
        "mS": mS,
        "mTh": mTh,
        "mHe": mHe,
        "mTr": mTr,
        "mTOT": mTOT
    }
    return weights




# %% ../../nbs/670_mass_clauser.ipynb #c4b311ce
def zatsiorsky(inputweight, inputheight):





    import csv
    import numpy as np



    actual_bodymass = inputweight  
    actual_height = inputheight  / 10
    # Coefficients for estimating the mass of body segments (B0, B1, B2, R, SD)
    #segment=[B0,B1,B2,R,SD]
    foot = [-0.829, 0.0077, 0.0073, 0.702, 0.101]
    shank = [-1.592, 0.0362, 0.0121, 0.872, 0.219]
    hip = [-2.649, 0.1463, 0.0137, 0.891, 0.721]
    hand = [-0.1165, 0.0036, 0.00175, 0.516, 0.063]
    forearm = [0.3185, 0.01445, -0.00114, 0.786, 0.101]
    upper_arm = [0.250, 0.03012, -0.0027, 0.837, 0.178]
    head = [1.296, 0.0171, 0.0143, 0.591, 0.322]
    upper_torso = [8.2144, 0.1862, -0.0584, 0.798, 1.142]
    middle_torso = [7.181, 0.2234, -0.0663, 0.828, 1.238]
    lower_torso = [-7.498, 0.0976, 0.04896, 0.743, 1.020]


    segment = [foot,shank,hip,hand,forearm,upper_arm,head,upper_torso,middle_torso,lower_torso]


  




    footW = segment[0][0] + segment[0][1]*actual_bodymass + segment[0][2]*actual_height
    shankW = segment[1][0] + segment[1][1]*actual_bodymass + segment[1][2]*actual_height
    hipW = segment[2][0] + segment[2][1]*actual_bodymass + segment[2][2]*actual_height
    handW = segment[3][0] + segment[3][1]*actual_bodymass + segment[3][2]*actual_height
    forearmW = segment[4][0] + segment[4][1]*actual_bodymass + segment[4][2]*actual_height
    upper_armW = segment[5][0] + segment[5][1]*actual_bodymass + segment[5][2]*actual_height
    headW = segment[6][0] + segment[6][1]*actual_bodymass + segment[6][2]*actual_height
    upper_torsoW = segment[7][0] + segment[7][1]*actual_bodymass + segment[7][2]*actual_height
    middle_torsoW = segment[8][0] + segment[8][1]*actual_bodymass + segment[8][2]*actual_height
    lower_torsoW = segment[9][0] + segment[9][1]*actual_bodymass + segment[9][2]*actual_height

    total_weight = (footW+shankW+hipW+handW+forearmW+upper_armW+handW)*2 + lower_torsoW+middle_torsoW+upper_torsoW+headW


    weightsZat = {

        "mTOTzat":total_weight ,
        "mHzat": handW,
        "mLAzat": forearmW,
        "mUAzat": upper_armW,
        "mFzat": footW,
        "mSzat": shankW,
        "mThzat": hipW,
        "mHezat": headW,
        "mUppTrzat": upper_torsoW,
        "mMidTrzat": middle_torsoW,
        "mLowTrzat": lower_torsoW,
        "mTOTzat": total_weight
    }
    return weightsZat



