# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/640_mass_plot_body.ipynb.

# %% auto #0
__all__ = ['project_root', 'plot_body']

# %% ../../nbs/640_mass_plot_body.ipynb #0e679fed
import sys
import os

# Adjust the path to point to the root where "anthromass" lives
project_root = os.path.abspath("..")  # because you're inside /nbs/
sys.path.append(project_root)


import matplotlib.pyplot as plt
from matplotlib.patches import Ellipse, Polygon
from .measurements_heights_module import *
from .com_calculation_module import *

# %% ../../nbs/640_mass_plot_body.ipynb #fb7021ee
def plot_body(Ansur, inputheight, gender):
    """
    Draws a front-view plot of the body segments with COM points.
    """
    m = get_measurements(Ansur, inputheight)
    heights = get_heights(Ansur, inputheight)
    pointsJC, com = get_joint_and_com_points(Ansur, inputheight, gender)
    m = m.iloc[0]
    heights = heights.iloc[0]
    #com = com.iloc[0]





    # Defines dimensions for drawing
    r1 = m["r1"]
    r2 = m["r2"]
    r3 = m["r3"]
    r4 = m["r4"]
    h8 = m["h8"]
    a1 = m["a1"]
    h1 = m["h1"]
    a2 = m["a2"]
    b2 = m["b2"]
    a3 = m["a3"]
    b3 = m["b3"]
    a4 = m["a4"]
    h3 = m["h3"]
    h4 = m["h4"]
    h6 = m["h6"]
    a5 = m["a5"]
    b5 = m["b5"]
    a8 = m["a8"]
    a9 = m["a9"]
    r1thigh = m["r1thigh"]
    r2thigh = m["r2thigh"]
    thighdelta = r1thigh - r2thigh





    # Use trunk height (base for head and arms) from get_heights
    TrunkH = heights["TrunkH"]
    UpperTrunkH = heights["UpperTrunkH"]
    MiddleTrunkH = heights["MiddleTrunkH"]
    LowerTrunkH = heights["LowerTrunkH"]
    ThighH = heights["ThighH"]
    ShankH = heights["ShankH"]
    UpperArmH = heights["UpperArmH"]
    LowerArmH = heights["LowerArmH"]
    NeckH = heights["NeckH"]
    HeadH = heights["head"]
    TotalH = heights["TotalH"]



    #width
    ShoulderW = m["acromialW"]
    HipW = m["hipW"]

    # COM points (2D projection)
    points = {
        "Upper Trunk": com["UTMC"],
        "Middle Trunk": com["MTMC"],
        "Lower Trunk": com["LTMC"],
        "Head": com["HeMC"],
        "Left Thigh": com["LTHMC"],
        "Thigh": com["RTHMC"],
        "Left Shank": com["LSHMC"],
        "Shank": com["RSHMC"],
        "Left Upper Arm": com["LUAMC"],
        "Upper Arm": com["RUAMC"],
        "Left Lower Arm": com["LLAMC"],
        "Lower Arm": com["RLAMC"],
        "Left Foot": com["LFMC"],
        "Foot": com["RFMC"],
        "Left Hand": com["LHMC"],
        "Hand": com["RHMC"],
        "Neck": com["NMC"]
    }





    





    #PLOTTING STARTS HERE


    # Create figure
    fig, ax = plt.subplots(figsize=(10, 10))




    # Plot COM points with extended leader lines and tweaked offsets
    for label, (x, y) in points.items():
        ax.scatter(x, y, color='red', s=20)
        if not label.startswith("Left"):
            # Adjust label position for specific labels
            if label == "Middle Trunk" or label == "Lower Arm":
                y_offset = 0.01
                x_offset = 0.4

            elif label == "Lower Trunk":
                y_offset = -0.08
                x_offset = 0.34

            elif label == "Thigh":
                y_offset = -0.1
                x_offset = 0.34


            elif label == "Hand":
                y_offset = 0.0
                x_offset = 0.34

            
            else:
                y_offset = 0.10
                x_offset = 0.24
            ax.annotate(
                label,
                xy=(x, y),
                xytext=(x + x_offset, y + y_offset),
                textcoords='data',
                fontsize=14,
                ha='left',
                va='bottom',
                arrowprops=dict(arrowstyle='-', lw=0.5, color='gray', shrinkA=0, shrinkB=2)
            )

    # Plot JC points with extended leader lines
    for label, (x, y) in pointsJC.items():
        ax.scatter(x, y, color='black', s=20)
        if not label.startswith("Right"):
            ax.annotate(
                label,
                xy=(x, y),
                xytext=(x - 0.24, y + 0.10),
                textcoords='data',
                fontsize=14,
                ha='right',
                va='bottom',
                arrowprops=dict(arrowstyle='-', lw=0.5, color='gray', shrinkA=0, shrinkB=2)
            )




    # Draw body segment shapes



    #Neck
    neck_coords = [
        (-a9, NeckH),
        (a9, NeckH),
        (a9, NeckH + a8),
        (-a9, NeckH + a8)
    ]
    ax.add_patch(Polygon(neck_coords, closed=True, fill=False, edgecolor='blue'))







    # Upper Trunk (Rectangle)
    upper_trunk_coords = [
        (-a1, UpperTrunkH),
        (a1, UpperTrunkH),
        (a1, UpperTrunkH + h1),
        (-a1, UpperTrunkH + h1)
    ]
    ax.add_patch(Polygon(upper_trunk_coords, closed=True, fill=False, edgecolor='blue'))

    # Middle Trunk (Trapezoid)
    middle_trunk_coords = [
        (-a2, MiddleTrunkH + m["h2"]),
        (a2, MiddleTrunkH + m["h2"]),
        (a3, MiddleTrunkH),
        (-a3, MiddleTrunkH)
    ]
    ax.add_patch(Polygon(middle_trunk_coords, closed=True, fill=False, edgecolor='green'))

    # Lower Trunk (Rectangle)
    lower_trunk_coords = [
        (-a4, LowerTrunkH),
        (a4, LowerTrunkH),
        (a4, LowerTrunkH + h3),
        (-a4, LowerTrunkH + h3)
    ]
    ax.add_patch(Polygon(lower_trunk_coords, closed=True, fill=False, edgecolor='blue'))


    BottomRightThigh = HipW-(r1thigh + r2thigh)
    BottomLeftThigh = HipW-(r1thigh - r2thigh)
    TopRightThigh = HipW - (2 * r1thigh)
    TopLeftThigh = HipW

    
    # Left Thigh (Rectangle)
    left_thigh_coords = [
        (-BottomLeftThigh, ThighH),                          #bottom left
        (-BottomRightThigh, ThighH),                         #bottom right
        (-TopRightThigh, ThighH + h4),                        #top right
        (-TopLeftThigh, ThighH + h4)                          #top left
    ]
    ax.add_patch(Polygon(left_thigh_coords, closed=True, fill=False, edgecolor='red'))

    # Right Thigh (Rectangle)
    right_thigh_coords = [
        (BottomLeftThigh, ThighH),
        (BottomRightThigh, ThighH),
        (TopRightThigh, ThighH + h4),
        (TopLeftThigh, ThighH + h4)
    ]
    ax.add_patch(Polygon(right_thigh_coords, closed=True, fill=False, edgecolor='red'))

    TopRightShank = BottomRightThigh
    TopLeftShank = BottomLeftThigh
    BottomLeftShank = TopLeftShank - (m["r1shank"]- m["r2shank"])
    BottoRightShank = TopRightShank - (m["r2shank"] - m["r1shank"])



    # Left Shank (Rectangle)
    left_shank_coords = [
        (-BottoRightShank, ShankH),
        (-BottomLeftShank, ShankH),
        (-TopLeftShank, ShankH + h6),
        (-TopRightShank, ShankH + h6)
    ]
    ax.add_patch(Polygon(left_shank_coords, closed=True, fill=False, edgecolor='red'))

    # Right Shank (Rectangle)
    right_shank_coords = [
        (BottoRightShank, ShankH),
        (BottomLeftShank, ShankH),
        (TopLeftShank, ShankH + h6),
        (TopRightShank, ShankH + h6)
    ]
    ax.add_patch(Polygon(right_shank_coords, closed=True, fill=False, edgecolor='red'))

    # Left Upper Arm (Rectangle)
    left_upperarm_coords = [
        (- ShoulderW - r2, UpperArmH),
        (- ShoulderW + r2, UpperArmH),
        (-ShoulderW + r1, UpperArmH + h8),
        (-ShoulderW - r1, UpperArmH + h8)
    ]
    ax.add_patch(Polygon(left_upperarm_coords, closed=True, fill=False, edgecolor='red'))

    # Right Upper Arm (Rectangle)
    right_upperarm_coords = [
        (ShoulderW - r2, UpperArmH),
        (ShoulderW + r2, UpperArmH),
        (ShoulderW + r1, UpperArmH + h8),
        (ShoulderW - r1, UpperArmH + h8)
    ]
    ax.add_patch(Polygon(right_upperarm_coords, closed=True, fill=False, edgecolor='red'))


    # Left Lower Arm (Rectangle)
    left_lowerarm_coords = [
        (-ShoulderW + r4, LowerArmH),
        (-ShoulderW -r4, LowerArmH),
        (- ShoulderW - r3, LowerArmH + m["h10"]),
        (- ShoulderW + r3, LowerArmH + m["h10"])
    ]
    ax.add_patch(Polygon(left_lowerarm_coords, closed=True, fill=False, edgecolor='red'))

    # Right Lower Arm (Rectangle)
    right_lowerarm_coords = [
        ( ShoulderW + r4, LowerArmH),
        (ShoulderW - r4, LowerArmH),
        (ShoulderW - r3, LowerArmH + m["h10"]),
        (ShoulderW + r3, LowerArmH + m["h10"])
    ]
    ax.add_patch(Polygon(right_lowerarm_coords, closed=True, fill=False, edgecolor='red'))

    # Left Foot (Ellipse)
    ax.add_patch(Ellipse((-(BottomLeftShank-m["r2shank"]), a5), b5 * 2, a5 * 2,
                         fill=False, edgecolor='purple', linewidth=1.5))
    # Right Foot (Ellipse)
    ax.add_patch(Ellipse(((BottomLeftShank-m["r2shank"]), a5), b5 * 2, a5 * 2,
                         fill=False, edgecolor='purple', linewidth=1.5))
    # Head (Ellipse) - position the head on top of the neck height
    ax.add_patch(Ellipse((0, HeadH + m["a7"]), m["b8"] * 2, m["a7"] * 2,
                         fill=False, edgecolor='purple', linewidth=1.5))
    


    # Left Hand (Ellipse) 
    ax.add_patch(Ellipse((-ShoulderW, LowerArmH-m["h9"]), m["b7"] * 2, m["h9"] * 2,
                         fill=False, edgecolor='purple', linewidth=1.5))
    
        #Right Hand (Ellipse) 
    ax.add_patch(Ellipse((ShoulderW, LowerArmH-m["h9"]), m["b7"] * 2, m["h9"] * 2,
                         fill=False, edgecolor='purple', linewidth=1.5))
    



            # Add custom legend
    from matplotlib.lines import Line2D

    legend_elements = [
        Line2D([0], [0], marker='o', color='w', label='Center of mass',
            markerfacecolor='red', markersize=6),
        Line2D([0], [0], marker='o', color='w', label='Joint center',
            markerfacecolor='black', markersize=6)
    ]

    ax.legend(handles=legend_elements, loc='upper right', fontsize=14)


    # Axes styling
    ax.axhline(0, color='black')
    #ax.axvline(0, color='black')
    ax.set_title("Body Segments with Center of Mass (Front view)")
    ax.set_xlabel("y")
    ax.set_ylabel("z")
    ax.set_xlim(-1.25, 1.25)
    ax.set_ylim(0, 2.5)
    ax.set_aspect('equal')
    ax.grid(True)





    plt.show()
    return pointsJC




