# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/620_mass_volume_calc.ipynb.

# %% auto #0
__all__ = ['get_volumes']

# %% ../../nbs/620_mass_volume_calc.ipynb #a54ccc6f
import numpy as np
from .measurements_heights_module import *

# %% ../../nbs/620_mass_volume_calc.ipynb #a7d42482
def get_volumes(Ansur, inputheight):

    #Computes the volumes for each body segment and the total volume.

    m = get_measurements(Ansur, inputheight)
    m=m.iloc[0]



    # Upper trunk volume
    vUT = np.pi * m["a1"] * m["b1"] * m["h1"]
    
    # Middle trunk volume (elliptical conical)
    vMT = (np.pi * m["h2"] / 3) * (m["a2"] * m["b2"] + m["a3"] * m["b3"] +
                                     np.sqrt(m["a2"] * m["b2"] * m["a3"] * m["b3"]))
    

    # Lower trunk volume (cylindrical approximation using both a4 and b4)
    vLT = np.pi * m["a4"] * m["b4"] * m["h3"]


    # Thigh volume
    r1thigh = m["r1thigh"]
    r2thigh = m["r2thigh"]
    vT = (np.pi * m["h4"] / 3) * (r1thigh**2 + r2thigh**2 + r1thigh * r2thigh)
    # Shank volume
    vS = (np.pi * m["h6"] / 3) * (m["r1shank"]**2 + m["r2shank"]**2 + m["r1shank"] * m["r2shank"])
    # Foot volume
    vF = (1/3) * np.pi * m["h7"] * (m["a5"] * m["b5"] + m["a6"] * m["b6"] +
                                     np.sqrt(m["a5"] * m["b5"] * m["a6"] * m["b6"]))
    # Upper arm volume
    vUA = (1/3) * np.pi * m["h8"] * (m["r1"]**2 + m["r2"]**2 + m["r1"] * m["r2"])

    # Hand (closed fist) volume (estimated as ellipsoid)
    vH = (4 / 3) * np.pi * (m["h9"]) * m["b7"]**2


    # Head volume 
    vHe = (4/3) * np.pi * (m["a7"]**2) * m["b8"]

    # Lower arm volume
    vLA = (1/3) * np.pi * m["h10"] * (m["r3"]**2 + m["r4"]**2 + m["r3"] * m["r4"])

    #Neck
    vN = np.pi*(m["a9"]**2)*m["a8"]

    
    volumes = {
        "vUT": vUT,
        "vMT": vMT,
        "vLT": vLT,
        "vT": vT,
        "vS": vS,
        "vF": vF,
        "vUA": vUA,
        "vH": vH,
        "vHe": vHe,
        "vN": vN,
        "vLA": vLA,
    }
    # Total volume (using your provided formula)
    vTOT = vHe+ vN + vUT + vMT + vLT + 2 * (vUA + vLA + vH + vT + vS + vF) #Here we use vHe2 instead of vHe + vN since the Modified hanvan model is intended to be used this way
    volumes["vTOT"] = vTOT
    return volumes

