# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/201_anthropometry.ipynb.

# %% auto 0
__all__ = ['make_pickle', 'measurement_names', 'make_model_formula', 'fit_model', 'predict_mean_bmb']

# %% ../nbs/201_anthropometry.ipynb 2
import pickle
import pandas as pd
import arviz as az
import bambi as bmb

# %% ../nbs/201_anthropometry.ipynb 4
def make_pickle(model, kindofmodel, measurement):
    with open(f'../output/anthro_models/{kindofmodel}/pickle_{measurement}_{kindofmodel}','wb') as file:
        pickle.dump(model,file)

# %% ../nbs/201_anthropometry.ipynb 6
def measurement_names():
    test=pd.read_csv('../data/processed/ANSURIItest.csv')
    test_var=test.iloc[:,1:94].drop('weightkg',axis=1).drop('stature',axis=1)
    col = test_var.columns[:]
    return col

# %% ../nbs/201_anthropometry.ipynb 9
def make_model_formula(measurement, formula:str):
    train=pd.read_csv('../data/processed/ANSURIIminusmeanstrain.csv')
    variables = f"{measurement} ~ " + formula
    made_model = bmb.Model(variables,data=train)
    return made_model

# %% ../nbs/201_anthropometry.ipynb 11
def fit_model(measurement, formula:str):
    made_model = make_model_formula(measurement, formula)
    made_fitted = made_model.fit(tune=2000, draws=2000, chains = 4, cores= 1, init="adapt_diag", progressbar=True)
    return made_fitted

# %% ../nbs/201_anthropometry.ipynb 13
def predict_mean_bmb(fitted, model, data, measurement):
    pred_df=pd.DataFrame()
    model.predict(fitted, data = data, kind='response')
    posterior_predictive = az.extract(fitted, group="posterior_predictive")
    predictions = posterior_predictive[measurement]
    mean_pred=[]
    for row in predictions:
        mean_pred.append(row.values.mean())    
    pred_df[measurement]=mean_pred
    return pred_df
