"""Fill in a module description here       yeeeeeee

Docs: https://jobindjohn.github.io/anthropmass/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['foo', 'boo']

# %% ../nbs/00_core.ipynb #31253ab4
def foo(): pass

# %% ../nbs/00_core.ipynb #cede88ba
def boo(): pass
