"""Docs: https://jobindjohn.github.io/anthropmass/data.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/110_data.ipynb.

# %% auto #0
__all__ = ['normalize', 'normalize_all', 'minus_mean', 'make_train_test']

# %% ../nbs/110_data.ipynb #27b6867a
import pandas as pd
from sklearn.model_selection import train_test_split

# %% ../nbs/110_data.ipynb #e97b7a1a
def normalize(data:pd.DataFrame, measurement:str):
    ansur=pd.read_csv('../data/processed/ANSURIImalefemale.csv')
    avg_m = ansur[measurement].mean()
    std_m = ansur[measurement].std()
    data[measurement] = (data[measurement] - avg_m) / std_m
    return data

# %% ../nbs/110_data.ipynb #fb838a1e-c91a-4e5b-a3fb-14d7a381ef8f
def normalize_all(data:pd.DataFrame, measurement:list):
    for m in measurement:
        data = normalize(data, m)
    return data

# %% ../nbs/110_data.ipynb #2129e90b
def minus_mean(data:pd.DataFrame, measurement:list):
    ansur=pd.read_csv('../data/processed/ANSURIImalefemale.csv')
    datacopy = data.copy()
    for m in measurement:
        avg_m = ansur[m].mean()
        datacopy[m] = datacopy[m].astype(float) - avg_m
    return datacopy

# %% ../nbs/110_data.ipynb #a7ef1ae2-945d-4652-877a-c766551be70b
def make_train_test(data:pd.DataFrame, test_size:float):
    train, test = train_test_split(data, test_size=test_size, shuffle=True, random_state=42)
    return train, test
